### ISSUE TITLE
Minimal lib?

### ISSUE THREAD

**Issue by mdewilde** [divStar/ico4a#3]
I've started using your library. However, as it is now packaged as an app, and as there were some conflicts with the app I'm working on, I reverted to copying over source.
I think it'd be nicer if I could declare your library as a dependency. Have you given thought to creating a minimal library (**aar**, I guess), and publishing it through maven central or jcenter?

I'm referring, in particular, to the contents of the ico4a package, which could very well stand on their own https://github.com/divStar/ico4a/tree/master/ico4a/src/main/java/divstar/ico4a

**Comment by divStar** [comment]
Hello there,

I have published the library on bintray in the jcenter repository quite a while ago. You can find it here: https://bintray.com/divstar/maven/ico4a/ .

You basically just include **jcenter()** and then add this dependency: "**compile 'divstar:ico4a:v1.0'**" to your application's build.gradle if I recall it correctly. As you can see, the **ico4a-v1.0.aar-file** in https://bintray.com/divstar/maven/ico4a/#files/divstar/ico4a/v1.0 is pretty small (33kb) since it only includes the necessary classes and no referenced libraries (I think there are none to reference).

I hope this solves your problem :).

P.s.: the library itself is packaged as an android library. The test-application is not supposed to be included in your final application at all (you may do so, but there is no reason to). All you should include is the minimal library either by copying over the aar-file and importing it through IntelliJ or - much simpler - just including jcenter and adding the dependency. I guess I should clarify this in the readme, which I will do one of these days.

**Comment by mdewilde** [comment]
Indeed there is a lib at jcenter, but that's where I ran (and still run) into two issues:

```
Attribute application@label value=(@string/ApplicationName) from AndroidManifest.xml:60:9-48 is also present at [divstar:ico4a:v1.0] AndroidManifest.xml:13:9-41 value=(@string/app_name).
Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:52:5-164:19 to override.

uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [divstar:ico4a:v1.0]
Suggestion: use tools:overrideLibrary="divstar.ico4a" to force usage
```

Rather than not being minimal, it seems there may be collision with the app_name string and the defined SDK. I found it strange that a lib should have those effects.
Perhaps you would consider not declaring the app name as a string resource? Also, is the minimum SDK a hard restriction?

**Comment by divStar** [comment]
I never really had any issues with the library as it is, but if you can make a diff, I will try it out locally and submit it once I saw it still works.

I am not entirely sure what you mean by hard restrictions and a minimum SDK. You are free to modify this library however you want and if you want, you can send me a pull request.

I am no android library expert - I just made it so it seemed usable. It may very well be that it contains things that may have side-effects. If you have encountered and solved it, let me know. If you have trouble solving it, let me know what your app configuration looks like and perhaps I can find a solution.

As it is now, I do not have enough information to help you :).

**Comment by mdewilde** [comment]
I went about this in a bit of a different way: I created a jar which declares com.google.android:android (http://mvnrepository.com/artifact/com.google.android/android) as a compile time dependency. That allows it to be compiled. As it is a compile time dependency, it doesn't pose a conflict with the eventual target runtime. It should work with any Android version that has Bitmap support (which should be all, as it was added in API 1: https://developer.android.com/reference/android/graphics/Bitmap.html).

One of the main thoughts on this is that aar is not really necessary, as you are not packaging any resources with the library. 

It's a bit hard to wrangle this diff into a pull request, as the changes are drastic, and I'm not sure as to how much change you'd accept.

I did use Maven because of familiarity and for quick prototyping.

[ico4a.zip](https://github.com/divStar/ico4a/files/533289/ico4a.zip)
